### Insert a new event
POST http://localhost:3000/events
Content-Type: application/json

{
  "name": "Sample Event",
  "dates": ["2020-12-31", "2021-01-01"]
}

### Add votes to an event
POST http://localhost:3000/events/35/vote
Content-Type: application/json

{
  "name": "Janet",
  "votes": [
    "2020-12-31",
    "2021-01-01"
  ]
}

### Add votes to an event
GET http://localhost:3000/events/35/results
Content-Type: application/json
